---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes
    
- name: "upgrade packages"
  become: yes
  apt:
    update_cache: yes

- name: "remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: true

- name: "install zip and unzip"
  become: yes
  apt:
    name: ["zip", "unzip"]
    state: latest
    update_cache: yes

- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 13.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_13.x bionic main
    update_cache: yes

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present

name: "Install NPM-distributed command-line tools"
  npm:
    global: yes
    name: "{{ item }}"
  
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    