- name: Update packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: safe

- name: Add Node.js apt key
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add Node.js 13.x ppa for apt repo
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_13.x focal main
    update_cache: yes

- name: Install Node.js
  become: yes
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: true
    state: present