---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes
    
- name: "upgrade packages"
  become: yes
  apt:
    update_cache: yes

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: true
  
- name: "install zip and unzip"
  become: yes
  apt:
    name: ["zip", "unzip"]
    state: latest
    update_cache: yes

- name: "fixed broken package"
  become: yes
  shell: |
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt-get update
    sudo apt-get install python2.7
    sudo apt-get install nodejs
  
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    