---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes
    
- name: "update package cache"
  become: yes
  apt:
    update_cache: yes

- name: "remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: true

- name: "install zip and unzip"
  become: yes
  apt:
    name: ["zip", "unzip"]
    state: latest
    update_cache: yes

- name: "install nodejs and npm."
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt-get install -y nodejs

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present