- name: unzip backend to the web directory
  unarchive:
    src: ~/project/backend.zip
    dest: /home/ubuntu
    
- name: Install Node and Build
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install -g npm@latest
    npm i
    npm run build
    
- name: Start PM2
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls