- name: unzip backend to the backend directory
  unarchive:
    src: ~/project/backend.zip
    dest: /home/ubuntu

- name: run build script
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build

- name: start pm2
  become: true
  shell: |
    cd /home/ubuntu/backend
    start npm --name backend -- run start
